change default node attribute to True
The task functions require a `with_task` attribute for some reason, without it you'll get the following error:

Using exact code from [the tutorial](https://joeflow.readthedocs.io/en/1.0.0/tutorial/workflow.html) 
```
[2020-09-26 16:58:45,108: INFO/ForkPoolWorker-3] Executing <Task: has_user (14)>
[2020-09-26 16:58:45,115: ERROR/ForkPoolWorker-3] Execution of <Task: has_user (14)> failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/joeflow/runner/celery.py", line 40, in _celery_task_runner
    result = node(workflow, **kwargs)
TypeError: has_user() missing 1 required positional argument: 'task'
[2020-09-26 16:58:45,121: INFO/ForkPoolWorker-3] Task joeflow.runner.celery._celery_task_runner[35944c6a-6638-40de-93ec-d5922224d523] succeeded in 0.03581299999495968s: None
```

This change fixes that but what is the reasoning behind the `with_task` attribute?